In [50]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print (data.shape)
print (target.shape)
print (set (target))


(150, 4)
(150,)
{'versicolor', 'virginica', 'setosa'}


In [51]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [52]:
from sklearn import tree

In [53]:
classifier = tree.DecisionTreeClassifier()
classifier.fit(data,t) # training on the iris dataset

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [54]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t
, test_size=0.2, random_state=0)

In [55]:
classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test

1.0


In [56]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [57]:
from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      1.00      1.00        13
  virginica       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30



In [60]:
# coding: utf-8

# In[1]:

from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print (data.shape)
print (target.shape)
print (set (target))


# In[2]:

t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3


# In[3]:

from sklearn.ensemble import AdaBoostClassifier
classifier = AdaBoostClassifier()
classifier.fit(data,t) # training on the iris dataset


# In[9]:

from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t
, test_size=0.2, random_state=0)


# In[10]:

classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test


# In[11]:

from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))


# In[12]:

from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))


# In[ ]:



(150, 4)
(150,)
{'versicolor', 'virginica', 'setosa'}
0.966666666667
[[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]
             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      0.93      0.96        14
  virginica       0.83      1.00      0.91         5

avg / total       0.97      0.97      0.97        30

